name: CI workflow for Python project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Deploy to production
        if: github.event_name == 'push' && github.event_ref == 'refs/heads/main'
        run: |
         echo "Deploying to production..."
          # Implement your deployment steps here

          # Your specific deployment steps for deploying a serverless application on AWS with Python
          # Ensure you have configured AWS credentials as secrets in your GitHub repository
          - name: Configure AWS credentials
            run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set region us-east-1

          - name: Package AWS SAM application
            run: sam build

          - name: Deploy AWS SAM application
            run: sam deploy --stack-name my-serverless-app --s3-bucket my-sam-bucket --capabilities CAPABILITY_IAM

          # Additional steps for monitoring and testing the deployment
          - name: Run integration tests
            run: pytest -m integration

          - name: Monitor application health
            run: aws cloudwatch get-metric-statistics --namespace AWS/Lambda --metric-name Duration --dimensions Name=FunctionName,Value=my-lambda-function --start-time $(date -u -d '1 hour ago' +%s) --end-time $(date -u +%s) --period 3600 --statistics Average